server:
  port: 8083
spring:
  datasource:
    url: jdbc:mariadb://mariadb-springboot-container:3306/bank
    username: app
    password: doquangduc123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true